import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IssueUI.java
 *
 * Created on May 13, 2010, 10:59:09 AM
 */

/**
 *
 * @author xp_system
 */
public class IssueUI extends javax.swing.JFrame {

    /** Creates new form IssueUI */
    public IssueUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMNo = new javax.swing.JTextField();
        txtMName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMStatus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMDate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtAcno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBTitle = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAuth1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        cmdExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        cmdIssue = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtIDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book issue form");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Select a Member");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 11, 104, -1));

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 33, 138, 151));

        jLabel11.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        jLabel11.setText("Select a Book");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 202, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Member No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));
        getContentPane().add(txtMNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 49, 47, -1));

        txtMName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMNameActionPerformed(evt);
            }
        });
        txtMName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtMNamePropertyChange(evt);
            }
        });
        txtMName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtMName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 178, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 82, -1, -1));

        txtMStatus.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        getContentPane().add(txtMStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 147, 31, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Status");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 148, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Membership Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 111, -1, -1));

        txtMDate.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        getContentPane().add(txtMDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 110, 100, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 605, 10));

        jLabel3.setText("Accession No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 209, -1, -1));
        getContentPane().add(txtAcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 39, -1));

        jLabel4.setText("Book Title");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 240, -1, -1));
        getContentPane().add(txtBTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 177, -1));

        jLabel12.setText("Pub ID.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 302, -1, -1));
        getContentPane().add(txtPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 73, -1));

        jLabel8.setText("Authors");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 271, -1, -1));
        getContentPane().add(txtAuth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 240, -1));

        jLabel9.setText("Status");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 302, -1, -1));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 24, -1));

        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });
        getContentPane().add(cmdExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jList2.setModel(new DefaultListModel());
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 224, 138, -1));

        cmdIssue.setText("Issue");
        cmdIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIssueActionPerformed(evt);
            }
        });
        getContentPane().add(cmdIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        jLabel13.setText("Enter Issue Date :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));
        getContentPane().add(txtIDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 112, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.PNG"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        setSize(new java.awt.Dimension(614, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Statement stmt = null;
    ResultSet rs = null;
    char st1 = 'N';
    char ms = 'Y';
    String SQL = "SELECT * FROM Member WHERE mem_issue = '" + st1 + "' and mem_status ='" + ms + "'";

    Statement stmt1 = null;
    ResultSet rs1 = null;
    char st = 'Y';  // Lib table
    String SQL1 = "SELECT * FROM Lib WHERE status = '" + st + "';";


    Statement stmt2 = null;
    ResultSet rs2 = null;
    String SQL2 = "SELECT * FROM Missue";

    Statement stmt3 = null;
    ResultSet rs3 = null;
    String SQL3 = "SELECT * FROM Tissue";


    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // getSelectedValue() method extracts the current cursor location value into a variable
        String MembNo = (String) jList1.getSelectedValue();
        // Extract the first 4 characters as Member No into a variable
        String Mno =MembNo.trim().substring(0, 3);
        String query = "SELECT * FROM Member WHERE memb_no = " + (Mno) + ";";
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/lib","root","admin");
            // Create SQL statement and execute query.
            stmt = con.createStatement();
            rs = stmt.executeQuery(query);

            if (rs.next()) {
                String MName = rs.getString("memb_name");
                String MDate = rs.getString("mdate");
                String MStatus = rs.getString("mem_status");
                // Displaying the contents in respective text boxes.
                txtMNo.setText(Mno);
                txtMName.setText(MName);
                txtMDate.setText(MDate);
                txtMStatus.setText(MStatus);
            } else {
                JOptionPane.showMessageDialog(null, "Record does not found in Member table");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jList1MouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        txtMNo.setEditable(false);
        txtMName.setEditable(false);
        txtMDate.setEditable(false);
        txtMStatus.setEditable(false);
        txtAcno.setEditable(false);
        txtBTitle.setEditable(false);
        txtAuth1.setEditable(false);
        txtPID.setEditable(false);
        txtStatus.setEditable(false);

        // dModel to perform DefaultListModel for Member
        // method operations
        DefaultListModel dModel = (DefaultListModel) jList1.getModel();
        // Method to add elements into jList1 control for member
        dModel.clear();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/lib","root","admin");

            // Listing Members
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                String Mno = rs.getString("memb_no");
                String MName = rs.getString("memb_name");
                // To make the Member no. as 4 digit because we will extract 4 digit from list value
		// in mouse click event.

                if (Mno.length() < 4)
                {
                    int x = Mno.length();
                    int nl = 4 - x;
                    while (nl > 0){
                        Mno = Mno + " ";
                        nl--;
                    }
                }
                dModel.addElement(Mno + "- " + MName);
            }
            jList1.setModel(dModel);


            // cModel to perform DefaultListModel for Library
            // method operations
            DefaultListModel cModel = (DefaultListModel) jList2.getModel();
            // Method to add elements into jList1 control for Library
            cModel.clear();

            // Listing books
            stmt1 = con.createStatement();
            rs1 = stmt1.executeQuery(SQL1);
            while (rs1.next()) {
                String Ano = rs1.getString("acc_no");
                String BTitle = rs1.getString("btitle");
                // To make the Accession no. as 4 digit because we will extract 4 digit from list value
		// in mouse click event.
                if (Ano.length() < 4)
                {
                    int x = Ano.length();
                    int nl = 4 - x;
                    while (nl > 0){
                        Ano = Ano + " ";
                        nl--;
                    }
                }
                cModel.addElement(Ano + "- " + BTitle);
            }
            jList2.setModel(cModel);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtMNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMNameActionPerformed

}//GEN-LAST:event_txtMNameActionPerformed

    private void txtMNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtMNamePropertyChange

}//GEN-LAST:event_txtMNamePropertyChange

    private void txtMNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMNameKeyPressed

}//GEN-LAST:event_txtMNameKeyPressed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cmdExitActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // getSelectedValue() method extracts the current cursor location value into a variable
        String MBook = (String) jList2.getSelectedValue();
        // Extract the first 4 characters as Accession number into a variable
        String Acno =MBook.trim().substring(0, 3);
        String query = "SELECT * FROM Lib WHERE acc_no = " + Acno + ";";
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/lib","root","admin");
            // Create SQL statement and execute query.
            stmt1 = con.createStatement();
            rs1 = stmt1.executeQuery(query);
            if (rs1.next()) {
                String bTitle = rs1.getString("btitle");
                String Auth1 = rs1.getString("author1");
                String PID = rs1.getString("pub_id");
                String PStatus = rs1.getString("status");
                // Displaying the contents in respective text boxes.
                txtAcno.setText(Acno);
                txtBTitle.setText(bTitle);
                txtAuth1.setText(Auth1);
                txtPID.setText(PID);
                txtStatus.setText(PStatus);
            } else {
                JOptionPane.showMessageDialog(null, "Record does not found in Libdent table");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void cmdIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIssueActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/lib","root","admin");
            // Missue table
            stmt2 = con.createStatement();
            rs2 = stmt.executeQuery(SQL);

            // Tissue table
            stmt3 = con.createStatement();
            rs3 = stmt.executeQuery(SQL);
            int Acno = Integer.parseInt(txtAcno.getText().trim());
            int Mno = Integer.parseInt(txtMNo.getText().trim());
            String idt = txtIDate.getText();
            String rdt = idt;  // Temporarily assigned for testing purpose
            int code = JOptionPane.showConfirmDialog(this, "Are you sure to add?", "Confirmation Dialog Box", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (code == JOptionPane.YES_OPTION) {
                // Record updated into Missue and Tissue tables
                String strSQL = "INSERT INTO Missue(acc_no, memb_no, idate, rdate) VALUES ("+(Acno)+", "+(Mno)+", '"+(idt)+"', '"+(rdt)+"')";
                String strSQL1 = "INSERT INTO Tissue(acc_no, memb_no, idate, rdate) VALUES ("+(Acno)+", "+(Mno)+", '"+(idt)+"', '"+(rdt)+"')";
                stmt2.executeUpdate(strSQL);
                stmt3.executeUpdate(strSQL1);

                // Change the status as library book issued
                char sta = 'N';  // Lib table
                String strSQLa = "Update Lib set status ='"+(sta)+"' where acc_no = " + (Acno);
                stmt1.executeUpdate(strSQLa);

                // Change the status as Member has a book
                char stb = 'Y';  // Member table
                String strSQLb = "Update Member set mem_issue ='"+(stb)+"' where memb_no = " + (Mno);
                stmt.executeUpdate(strSQLb);
                JOptionPane.showMessageDialog(this, "Record update successfully");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdIssueActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdIssue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAcno;
    private javax.swing.JTextField txtAuth1;
    private javax.swing.JTextField txtBTitle;
    private javax.swing.JTextField txtIDate;
    private javax.swing.JTextField txtMDate;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMNo;
    private javax.swing.JTextField txtMStatus;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

}
