import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LibUI.java
 *
 * Created on May 3, 2010, 12:16:15 PM
 */

/**
 *
 * @author xp_system
 */
public class LibUI extends javax.swing.JFrame {

    /** Creates new form LibUI */
    public LibUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // for table Lib
    Statement stmt = null;
    ResultSet rs = null;
    String SQL = "SELECT * FROM Lib";
    // for table Publisher
    Statement stmt1 = null;
    ResultSet rs1 = null;
    String SQL1 = "SELECT * FROM publisher";

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdExit = new javax.swing.JButton();
        cmdEdit = new javax.swing.JButton();
        cmdSave = new javax.swing.JButton();
        cmdNew = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAcno = new javax.swing.JTextField();
        txtBTitle = new javax.swing.JTextField();
        txtAuth1 = new javax.swing.JTextField();
        txtAuth2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        txtPages = new javax.swing.JTextField();
        txtEdition = new javax.swing.JTextField();
        txtPDate = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        cmdDelete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Libary Console");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });
        getContentPane().add(cmdExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        cmdEdit.setText("Edit");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });
        getContentPane().add(cmdEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 270, -1, -1));

        cmdSave.setText("Save");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        cmdNew.setText("New");
        cmdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNewActionPerformed(evt);
            }
        });
        getContentPane().add(cmdNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 270, -1, -1));

        cmdClear.setText("Clear");
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });
        getContentPane().add(cmdClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 270, 70, -1));

        jLabel1.setText("Accession No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, -1, -1));

        jLabel2.setText("Book Title");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 45, -1, -1));

        jLabel3.setText("Authors");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 83, -1, -1));

        jLabel4.setText("Publisher");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 142, -1, -1));

        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 180, -1, -1));

        jLabel6.setText("Purchase Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, -1, -1));

        jLabel7.setText("Pages");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 180, -1, -1));

        jLabel8.setText("Edition");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 180, -1, -1));

        jLabel9.setText("Status");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 211, -1, -1));
        getContentPane().add(txtAcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 39, -1));
        getContentPane().add(txtBTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 42, 231, -1));
        getContentPane().add(txtAuth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 245, -1));
        getContentPane().add(txtAuth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 111, 245, -1));

        jComboBox1.setModel(new DefaultComboBoxModel() );
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 139, 231, -1));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 177, 61, -1));
        getContentPane().add(txtPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 177, 47, -1));
        getContentPane().add(txtEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 177, 57, -1));
        getContentPane().add(txtPDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 208, 80, -1));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 208, 24, -1));

        cmdDelete.setText("Delete");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(cmdDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.PNG"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 320));

        setSize(new java.awt.Dimension(493, 356));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cmdExitActionPerformed

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        this.setVisible(false);
        new LibEditUI().setVisible(true);
}//GEN-LAST:event_cmdEditActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/lib","root","admin");
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);
            int Acno = Integer.parseInt(txtAcno.getText().trim());
            String bTitle = txtBTitle.getText();
            String Auth1 = txtAuth1.getText();
            String Auth2 = txtAuth2.getText();
            // Creating a String object pName
            String pName = (String) jComboBox1.getSelectedItem();
            // Extract the first 4 characters as publisher number into a variable
            String PubNo = String.valueOf(pName.substring(0, 3).trim());
            int pno = Integer.parseInt(PubNo);
            jLabel10.setText(""+pno);
            float Price = Float.parseFloat(txtPrice.getText());
            int pages = Integer.parseInt(txtPages.getText());
            int edition = Integer.parseInt(txtEdition.getText());
            String Pdate = txtPDate.getText();
            char BStatus = 'Y';
            int code = JOptionPane.showConfirmDialog(this, "Are you sure to add?", "Confirmation Dialog Box", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (code == JOptionPane.YES_OPTION) {
                String strSQL = "INSERT INTO Lib(acc_no, btitle, author1, author2, pub_id, price, pdate, pages, edition, status) VALUES ("+(Acno)+", '"+(bTitle)+"', '"+(Auth1)+"', '"+(Auth2)+"', "+(pno)+", "+(Price)+", '"+(Pdate)+"', "+(pages)+", "+(edition)+", '"+(BStatus)+"')";
                int rowsEffected = stmt.executeUpdate(strSQL);
                JOptionPane.showMessageDialog(this, "Record added successfully into Lib table");
            }
            cmdSave.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void cmdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNewActionPerformed
        
        cmdSave.setEnabled(true);
        DefaultComboBoxModel cModel = (DefaultComboBoxModel) jComboBox1.getModel();
        cModel.removeAllElements();
        txtStatus.setEditable(false);
        
        cmdSave.setEnabled(true);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/lib","root","admin");
    
            stmt = con.createStatement();   
            rs = stmt.executeQuery(SQL);
            int acno=0, ACNO = 0;
            while (rs.next()) {
                ACNO = rs.getInt("acc_no");
            }
            ACNO++;
            acno = ACNO;
            txtAcno.setText(Integer.toString(acno));
            stmt1 = con.createStatement();   // To list publishers in JComboBox1 component
            rs1 = stmt1.executeQuery(SQL1);
            while (rs1.next()) {
                String pubno = rs1.getString("pub_id");
                String pubName = rs1.getString("pub_name");
                // To make the publisher no. as 4 digit because we will extract 4 digit from list value
		// in mouse click event
                txtStatus.setText("Y"); // Because it is a new book, when it will be issue,
                // it's status will be N.
                if (pubno.length() < 4)
                {
                    int x = pubno.length();
                    int nl = 4 - x;
                    while (nl > 0){
                        pubno = pubno + " ";
                        nl--;
                    }
                }
                cModel.addElement(pubno + "- " + pubName);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
}//GEN-LAST:event_cmdNewActionPerformed

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        DefaultComboBoxModel cModel = (DefaultComboBoxModel) jComboBox1.getModel();
        txtAcno.setText("");
        txtBTitle.setText("");
        txtAuth1.setText("");
        txtAuth2.setText("");
        cModel.removeAllElements();
        txtPrice.setText("");
        txtPages.setText("");
        txtEdition.setText("");
        txtPDate.setText("");
        txtStatus.setText("");
        cmdSave.setEnabled(false);
}//GEN-LAST:event_cmdClearActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        txtAcno.setEditable(false);
        // Deactivate the Save button when form loads
        cmdSave.setEnabled(false);
    }//GEN-LAST:event_formWindowGainedFocus

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        this.setVisible(false);
        new LibDelUI().setVisible(true);

    }//GEN-LAST:event_cmdDeleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdNew;
    private javax.swing.JButton cmdSave;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAcno;
    private javax.swing.JTextField txtAuth1;
    private javax.swing.JTextField txtAuth2;
    private javax.swing.JTextField txtBTitle;
    private javax.swing.JTextField txtEdition;
    private javax.swing.JTextField txtPDate;
    private javax.swing.JTextField txtPages;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

}
