
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vivek kumar
 */
public class shop_purchase extends javax.swing.JFrame {

    /**
     * Creates new form shop_purchase
     */
    public shop_purchase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        r1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        jTextField3.setText("jTextField1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 23, 90, 32));

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 296, 81, 32));

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("mobile");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 81, 32));

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 134, 81, 32));

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("product name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 234, 90, 32));

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("state");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 184, 81, 32));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 134, 220, 32));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 23, 220, 32));

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 220, 32));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 84, 220, 32));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 184, 220, 32));

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TV", "HEADPHONE", "CAMERA", "LAPTOP", " ", "TSHIRT", "SPORTS SHOE", "LEATHER JACKET", "SUNGLASSES", " ", "SAREE", "SALWAR SUIT", "LEHENGA", "PURSE", "WATCH", " ", "BAT", "BALL", "FOOTBALL", "PADS" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 220, 38));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("BUY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 94, 38));

        r1.setForeground(new java.awt.Color(255, 255, 51));
        r1.setText("USE WALLET");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 440));

        setSize(new java.awt.Dimension(505, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TO^DO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new shop_order().setVisible(true); 


 try
{ Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lib","root","admin");
Statement st=con.createStatement();
            Double a=Double.parseDouble(t5.getText());
            Double w=0.02*a;
    
 int x=st.executeUpdate("insert into wallet values('"+w+"') ;");
ResultSet rs=st.executeQuery("select * from wallet ;");



while(rs.next())
{   String  c=rs.getString("price");
    
 
}



}catch (Exception e)
{
} 









// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
if(c1.getSelectedItem().equals("TV"))
{
    t5.setText("11990");
}

if(c1.getSelectedItem().equals("HEADPHONE"))
{
    t5.setText("2680");
}

if(c1.getSelectedItem().equals("CAMERA"))
{
    t5.setText("283990");
}
if(c1.getSelectedItem().equals("LAPTOP"))
{
    t5.setText("128000");
}






if(c1.getSelectedItem().equals("TSHIRT"))
{
    t5.setText("439");
}
  
if(c1.getSelectedItem().equals("SPORTS SHOE"))
{
    t5.setText("1199");
}

if(c1.getSelectedItem().equals("LEATHER JACKET"))
{
    t5.setText("2499");
}

if(c1.getSelectedItem().equals("SUNGLASSES"))
{
    t5.setText("734");
}



if(c1.getSelectedItem().equals("SAREE"))
{
    t5.setText("1050");
}

if(c1.getSelectedItem().equals("SALWAR SUIT"))
{
    t5.setText("618");
}

if(c1.getSelectedItem().equals("LEHENGA"))
{
    t5.setText("1740");
}

if(c1.getSelectedItem().equals("HEELS"))
{
    t5.setText("490");
}

if(c1.getSelectedItem().equals("PURSE"))
{
    t5.setText("2204");
}

if(c1.getSelectedItem().equals("WATCH"))
{
    t5.setText("5495");
}





if(c1.getSelectedItem().equals("BAT"))
{
    t5.setText("11728");
}

if(c1.getSelectedItem().equals("BALL"))
{
    t5.setText("699");
}

if(c1.getSelectedItem().equals("FOOTBALL"))
{
    t5.setText("545");
}

if(c1.getSelectedItem().equals("PADS"))
{
    t5.setText("2990");
}

// TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
if(r1.isSelected())
{new WALLETUSE().setVisible(true);
}




        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shop_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shop_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shop_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shop_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shop_purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton r1;
    public static javax.swing.JTextField t1;
    public static javax.swing.JTextField t2;
    public static javax.swing.JTextField t3;
    public static javax.swing.JTextField t4;
    public static javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
